export enum ERegion {
  VINNYTSIA = 'Vinnytsia',
  VOLYN = 'Volyn',
  DNIPROPETROVSK = 'Dnipro',
  DONETSK = 'Donetsk',
  ZHYTOMYR = 'Zhytomyr',
  ZAPORIZHZHIA = 'Zaporizhzhia',
  IVANO_FRANKIVSK = 'Ivano-Frankivsk',
  KYIV = 'Kyiv',
  KIROVOHRAD = 'Kirovohrad',
  LUGANSK = 'Luhansk',
  LVOV = 'Lviv',
  MYKOLAIV = 'Mykolaiv',
  ODESA = 'Odesa',
  POLTAVA = 'Poltava',
  RIVNE = 'Rivne',
  SUMY = 'Sumy',
  TERNOPIL = 'Ternopil',
  KHARKIV = 'Kharkiv',
  CHERKASY = 'Cherkasy',
  CHERNIHIV = 'Chernihiv',
  CHERNIVTSI = 'Chernivtsi',
  KHERSON = 'Kherson',
  ZAKARPATTIA = 'Zakarpattia',
  KHMELNYTSKYI = 'Khmelnytskyi',
}
